<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $payload['title'] }} | Supply Chain Intelligence</title>
<style>
@page{size:A4 landscape;margin:15mm}*{box-sizing:border-box}body{margin:0;color:#17293b;font-family:Arial,sans-serif;font-size:9px}.toolbar{display:flex;align-items:center;justify-content:space-between;margin:16px auto;padding:12px 16px;max-width:1200px;border:1px solid #cbd9e5;border-radius:8px;background:#f4f8fb}.toolbar strong,.toolbar span{display:block}.toolbar strong{font-size:13px}.toolbar span{margin-top:3px;color:#718396;font-size:8px}.toolbar button{padding:9px 15px;border:0;border-radius:7px;background:#176fd1;color:#fff;font-weight:bold;cursor:pointer}.sheet{margin:auto;max-width:1200px}.header{padding:17px 19px;border-radius:8px;background:#071a2d;color:#fff}.header table{width:100%}.header small{color:#54a9f5;font-size:7px;font-weight:bold;letter-spacing:1.2px}.header h1{margin:5px 0 3px;font-size:20px}.header p{margin:0;color:#8ba8c0;font-size:8px}.meta{text-align:right}.meta strong,.meta span{display:block}.meta span{margin-top:4px;color:#7898b3;font-size:7px}.filters{margin:9px 0;padding:7px 10px;border:1px solid #d7e2eb;border-radius:5px;background:#f7f9fb;color:#63788b}.metrics{width:100%;margin:0 0 11px;border-collapse:separate;border-spacing:6px 0}.metrics td{padding:9px 11px;border:1px solid #d8e3ed;border-left:4px solid #267ed8;border-radius:6px}.metrics small,.metrics strong{display:block}.metrics small{color:#73869a;font-size:6px;font-weight:bold;letter-spacing:.5px;text-transform:uppercase}.metrics strong{margin-top:3px;color:#10283e;font-size:15px}.notice{margin:8px 0;padding:7px 9px;border:1px solid #efd899;border-radius:5px;background:#fff7dc;color:#795e16}.section-title{margin:12px 0 6px;color:#153551;font-size:10px}table.data{width:100%;border-collapse:collapse;table-layout:fixed}.data th{padding:7px 5px;background:#0b2943;color:#adcce4;font-size:6px;letter-spacing:.5px;text-align:left;text-transform:uppercase}.data td{padding:6px 5px;border-bottom:1px solid #e1e8ef;color:#45596d;vertical-align:top;word-break:break-word}.data tr:nth-child(even) td{background:#f7f9fb}.name{color:#172d42;font-weight:bold}.sub{display:block;margin-top:2px;color:#8796a5;font-size:6px}.pill{display:inline-block;padding:3px 6px;border-radius:9px;font-size:6px;font-weight:bold}.low,.positive,.active{background:#def6e9;color:#148047}.medium,.neutral,.limited{background:#fff0c9;color:#946400}.high,.negative,.inactive{background:#ffe1e4;color:#c4303b}.footer{margin-top:10px;padding-top:6px;border-top:1px solid #dce4eb;color:#8291a0;font-size:6px}.footer span{float:right}@media print{.toolbar{display:none}.sheet{max-width:none}.no-print{display:none}body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style>
</head>
<body>
<div class="toolbar"><div><strong>{{ $payload['title'] }}</strong><span>Gunakan dialog browser dan pilih “Save as PDF” untuk menyimpan laporan.</span></div><button onclick="window.print()">Print / Save as PDF</button></div>
<main class="sheet">
<header class="header"><table><tr><td><small>SUPPLY CHAIN INTELLIGENCE · REPORT CENTER</small><h1>{{ $payload['title'] }}</h1><p>Operational intelligence generated from the current application dataset.</p></td><td class="meta"><strong>{{ $generatedAt->format('d M Y, H:i') }} WIB</strong><span>Prepared by {{ auth()->user()?->name ?? 'System User' }}</span><span>Confidential analytical report</span></td></tr></table></header>
@if(collect($filters)->filter()->isNotEmpty())<div class="filters"><b>Filters:</b> @foreach(collect($filters)->filter() as $key=>$value) {{ ucfirst($key) }} = {{ $value }}@if(!$loop->last) · @endif @endforeach</div>@else<div class="filters"><b>Scope:</b> Complete available dataset.</div>@endif
<table class="metrics"><tr>@foreach($payload['metrics'] as $label=>$value)<td><small>{{ $label }}</small><strong>{{ $value }}</strong></td>@endforeach</tr></table>
@if($payload['notice']??null)<div class="notice">{{ $payload['notice'] }}</div>@endif
<h2 class="section-title">Detailed Records · {{ number_format($payload['rows']->count()) }}</h2>

@if(in_array($type,['executive','risk']))
<table class="data"><thead><tr><th>#</th><th>Country</th><th>Region</th><th>Risk Score</th><th>Risk Level</th>@if($type==='risk')<th>Weather</th><th>Inflation</th><th>News</th><th>Currency</th><th>Source</th>@endif</tr></thead><tbody>
@foreach($payload['rows'] as $row) @php $snap=$row->riskScores?->first(); @endphp<tr><td>{{ $loop->iteration }}</td><td><span class="name">{{ $row->country_name }}</span><span class="sub">{{ $row->country_code }}</span></td><td>{{ $row->region ?: 'Global' }}</td><td>{{ number_format($snap?->total_score ?? $row->risk_index,1) }}/100</td><td><span class="pill {{ strtolower($row->risk_level) }}">{{ $row->risk_level }}</span></td>@if($type==='risk')<td>{{ $snap?->weather_risk ?? 'Not measured' }}</td><td>{{ $snap?->inflation_risk ?? 'Not measured' }}</td><td>{{ $snap?->news_risk ?? 'Not measured' }}</td><td>{{ $snap?->currency_risk ?? 'Not measured' }}</td><td>{{ $snap?'Measured':'Estimated' }}</td>@endif</tr>@endforeach
</tbody></table>
@elseif($type==='economy')
<table class="data"><thead><tr><th>#</th><th>Economy</th><th>Region</th><th>GDP</th><th>Population</th><th>Growth</th><th>Inflation</th><th>Trade/GDP</th><th>Exports</th><th>Imports</th><th>Year</th></tr></thead><tbody>@foreach($payload['rows'] as $row)<tr><td>{{ $loop->iteration }}</td><td><span class="name">{{ $row->country_name }}</span><span class="sub">{{ $row->country_code }}</span></td><td>{{ $row->region }}</td><td>{{ $row->gdp!==null?'$'.number_format($row->gdp):'Not reported' }}</td><td>{{ $row->population!==null?number_format($row->population):'Not reported' }}</td><td>{{ $row->gdp_growth!==null?number_format($row->gdp_growth,2).'%':'Not reported' }}</td><td>{{ $row->inflation_rate!==null?number_format($row->inflation_rate,2).'%':'Not reported' }}</td><td>{{ $row->trade_percentage!==null?number_format($row->trade_percentage,1).'%':'Not reported' }}</td><td>{{ $row->exports_value!==null?'$'.number_format($row->exports_value):'Not reported' }}</td><td>{{ $row->imports_value!==null?'$'.number_format($row->imports_value):'Not reported' }}</td><td>{{ $row->economic_data_year??'N/A' }}</td></tr>@endforeach</tbody></table>
@elseif($type==='ports')
<table class="data"><thead><tr><th>#</th><th>Code</th><th>Facility</th><th>Country / City</th><th>Type</th><th>Capacity</th><th>Status</th><th>Risk</th></tr></thead><tbody>@foreach($payload['rows'] as $row)<tr><td>{{ $loop->iteration }}</td><td>{{ $row->port_code?:'N/A' }}</td><td class="name">{{ $row->port_name }}</td><td>{{ $row->country }}<span class="sub">{{ $row->city }}</span></td><td>{{ $row->port_type }}</td><td>{{ $row->annual_capacity?number_format($row->annual_capacity).' TEU':'Not reported' }}</td><td><span class="pill {{ strtolower($row->status) }}">{{ $row->status }}</span></td><td>{{ $row->risk_index }}/100</td></tr>@endforeach</tbody></table>
@elseif($type==='news')
<table class="data"><thead><tr><th>#</th><th>Title</th><th>Keyword</th><th>Sentiment</th><th>Published</th><th>Source URL</th></tr></thead><tbody>@foreach($payload['rows'] as $row)<tr><td>{{ $loop->iteration }}</td><td class="name">{{ $row->title }}</td><td>{{ $row->keyword }}</td><td><span class="pill {{ strtolower($row->sentiment) }}">{{ $row->sentiment }}</span></td><td>{{ $row->published_at?->format('d M Y')??'N/A' }}</td><td>{{ \Illuminate\Support\Str::limit($row->url,70) }}</td></tr>@endforeach</tbody></table>
@elseif($type==='watchlist')
<table class="data"><thead><tr><th>#</th><th>Country</th><th>Region</th><th>Capital</th><th>Currency</th><th>Population</th><th>Risk</th><th>Level</th></tr></thead><tbody>@foreach($payload['rows'] as $row) @php $country=$row->country; @endphp<tr><td>{{ $loop->iteration }}</td><td class="name">{{ $country?->country_name }}</td><td>{{ $country?->region }}</td><td>{{ $country?->capital }}</td><td>{{ $country?->currency }}</td><td>{{ $country?->population?number_format($country->population):'Not reported' }}</td><td>{{ $country?->risk_index }}/100</td><td><span class="pill {{ strtolower($country?->risk_level) }}">{{ $country?->risk_level }}</span></td></tr>@endforeach</tbody></table>
@elseif($type==='articles')
<table class="data"><thead><tr><th>#</th><th>Title</th><th>Category</th><th>Author</th><th>Summary</th><th>Published</th></tr></thead><tbody>@foreach($payload['rows'] as $row)<tr><td>{{ $loop->iteration }}</td><td class="name">{{ $row->title }}</td><td>{{ $row->category }}</td><td>{{ $row->author }}</td><td>{{ \Illuminate\Support\Str::limit(strip_tags($row->content),160) }}</td><td>{{ $row->created_at?->format('d M Y H:i') }}</td></tr>@endforeach</tbody></table>
@elseif($type==='users')
<table class="data"><thead><tr><th>#</th><th>Name</th><th>Email</th><th>Role</th><th>Department</th><th>Status</th><th>Last Login</th></tr></thead><tbody>@foreach($payload['rows'] as $row)<tr><td>{{ $loop->iteration }}</td><td class="name">{{ $row->name }}</td><td>{{ $row->email }}</td><td>{{ $row->role }}</td><td>{{ $row->department }}</td><td>{{ $row->status }}</td><td>{{ $row->last_login_at?->format('d M Y H:i') ?? 'Never' }}</td></tr>@endforeach</tbody></table>
@endif
@if($payload['rows']->isEmpty())<p>No records match the selected report filter.</p>@endif
<footer class="footer">Supply Chain Intelligence Report Center<span>Generated {{ $generatedAt->toDateTimeString() }}</span></footer>
</main>
</body></html>
