@extends('layouts.bootstrap5')
@section('title','Global Weather Map')
@section('content_header')
<div class="wm-head"><div><span>LIVE GEOSPATIAL INTELLIGENCE</span><h1>Global Weather Operations Map</h1><p>Monitor rain, thunderstorms, and high-wind exposure across {{ number_format($weatherPoints->count()) }} countries.</p></div><div><span class="wm-live"><i></i> Open-Meteo live</span><a href="{{ route('weather.index') }}"><i class="fas fa-list"></i> Country Directory</a></div></div>
@stop
@section('content')
<div class="wm-stats">
 <article><i class="fas fa-satellite-dish blue"></i><div><span>Observations</span><strong>{{ number_format($weatherPoints->count()) }}</strong><small>national reporting points</small></div></article>
 <article><i class="fas fa-cloud-rain cyan"></i><div><span>Rain Exposure</span><strong>{{ number_format($rainCount) }}</strong><small>active precipitation</small></div></article>
 <article><i class="fas fa-bolt purple"></i><div><span>Storm Alerts</span><strong>{{ number_format($stormCount) }}</strong><small>thunderstorm conditions</small></div></article>
 <article><i class="fas fa-wind orange"></i><div><span>Strong Wind</span><strong>{{ number_format($windCount) }}</strong><small>wind ≥40 or gust ≥60 km/h</small></div></article>
</div>
<section class="wm-shell">
 <header class="wm-toolbar"><div><span>INTERACTIVE WEATHER NETWORK</span><h2>Current Global Conditions</h2></div><label><i class="fas fa-globe-americas"></i><select id="weatherCountryFilter"><option value="">All countries</option>@foreach($mapCountries as $country)<option value="{{ $country['code'] }}">{{ $country['name'] }} — {{ $country['code'] }}</option>@endforeach</select></label><button id="resetWeatherMap"><i class="fas fa-undo"></i> Reset</button><button id="weatherMapFullscreen"><i class="fas fa-expand"></i> Fullscreen</button></header>
 <div class="wm-layers">
  <button class="active" data-weather-layer="observations"><i class="fas fa-map-marker-alt"></i> Observations <b id="observationLayerCount">{{ $weatherPoints->count() }}</b></button>
  <button class="active rain" data-weather-layer="rain"><i class="fas fa-cloud-rain"></i> Rain <b id="rainLayerCount">{{ $rainCount }}</b></button>
  <button class="active storm" data-weather-layer="storm"><i class="fas fa-bolt"></i> Storm <b id="stormLayerCount">{{ $stormCount }}</b></button>
  <button class="active wind" data-weather-layer="wind"><i class="fas fa-wind"></i> Strong wind <b id="windLayerCount">{{ $windCount }}</b></button>
  <button class="active radar" id="radarLayerToggle"><i class="fas fa-broadcast-tower"></i> Live rain radar <b id="radarStatus">...</b></button>
  <span><i></i> <strong id="weatherVisibleCount">{{ $weatherPoints->count() }}</strong> observations visible</span>
 </div>
 <div class="wm-stage"><div id="globalWeatherMap"></div><aside class="wm-legend"><strong>MAP LEGEND</strong><span><i class="observation"></i> Observation</span><span><i class="rain"></i> Rain / showers</span><span><i class="storm"></i> Thunderstorm</span><span><i class="wind"></i> Strong wind</span></aside><div id="weatherMapEmpty" class="wm-empty" hidden><i class="fas fa-cloud-sun"></i><strong>No live observation</strong><span>Choose another country.</span></div></div>
 <footer><span><i class="fas fa-sync-alt"></i> Data cached for 15 minutes</span><span id="radarTimestamp"><i class="fas fa-broadcast-tower"></i> Loading latest radar frame...</span><a href="https://www.rainviewer.com/" target="_blank" rel="noopener">Radar by RainViewer</a><a href="https://open-meteo.com/" target="_blank" rel="noopener">Open-Meteo source <i class="fas fa-external-link-alt"></i></a></footer>
</section>
@stop
@section('css')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
.wm-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:15px}.wm-head>div:first-child>span,.wm-toolbar>div>span{color:#218cff;font-size:9px;font-weight:850;letter-spacing:1.3px}.wm-head h1{margin:4px 0 3px;color:#f1f7fd;font-size:25px;font-weight:800}.wm-head p{margin:0;color:#7695b1;font-size:11px}.wm-head>div:last-child{display:flex;gap:9px}.wm-head a,.wm-live{padding:9px 11px;border:1px solid #285274;border-radius:8px;background:#0b243a;color:#9dc9ec;font-size:9px;font-weight:750}.wm-head a:hover{background:#1479f8;color:#fff;text-decoration:none}.wm-live{border-color:#18583b;background:#0a2b21;color:#5ce49a}.wm-live i,.wm-layers>span>i{display:inline-block;width:7px;height:7px;margin-right:4px;border-radius:50%;background:#22c875;box-shadow:0 0 0 3px rgba(34,200,117,.15)}
.wm-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-bottom:13px}.wm-stats article{display:flex;align-items:center;padding:14px;border:1px solid #1b3d59;border-radius:12px;background:linear-gradient(145deg,#0d2238,#081725);box-shadow:0 10px 24px rgba(0,0,0,.15)}.wm-stats article>i{display:grid;place-items:center;width:43px;height:43px;margin-right:10px;border-radius:11px;font-size:16px}.wm-stats .blue{background:#113b63;color:#50a9ff}.wm-stats .cyan{background:#0a3c47;color:#45d0e8}.wm-stats .purple{background:#302653;color:#a88aff}.wm-stats .orange{background:#472d15;color:#ffad52}.wm-stats span,.wm-stats small{display:block;color:#7291ad;font-size:8px}.wm-stats strong{display:block;color:#f0f7fe;font-size:19px;line-height:21px}.wm-stats small{color:#54728d}
.wm-shell{overflow:hidden;border:1px solid #1b3d59;border-radius:13px;background:#081725;box-shadow:0 15px 35px rgba(0,0,0,.18)}.wm-toolbar{display:flex;align-items:center;gap:9px;padding:14px;border-bottom:1px solid #1b3d59;background:#0b1f33}.wm-toolbar>div{margin-right:auto}.wm-toolbar h2{margin:2px 0 0;color:#edf6ff;font-size:15px}.wm-toolbar label{display:flex;align-items:center;width:250px;height:37px;margin:0;padding:0 10px;border:1px solid #28506e;border-radius:9px;background:#071726;color:#3f9ef5}.wm-toolbar select{width:100%;margin-left:7px;border:0;outline:0;background:#071726;color:#dce9f5;font-size:9px}.wm-toolbar select option{background:#091a2c}.wm-toolbar button{height:37px;padding:0 11px;border:1px solid #28506e;border-radius:9px;background:#0b2942;color:#8dbfe7;font-size:9px;font-weight:750}.wm-toolbar button:hover{border-color:#1684ff;background:#123d61;color:#fff}.wm-layers{display:flex;align-items:center;gap:7px;padding:9px 14px;border-bottom:1px solid #17354d;background:#071624}.wm-layers button{height:33px;padding:0 9px;border:1px solid #244963;border-radius:8px;background:#0b2237;color:#7897b3;font-size:8px;opacity:.5}.wm-layers button.active{border-color:#347caf;color:#e5f3ff;opacity:1;box-shadow:0 0 0 3px rgba(34,132,226,.07)}.wm-layers button.rain i{color:#2d9cff}.wm-layers button.storm i{color:#a178ff}.wm-layers button.wind i{color:#ff9f3f}.wm-layers b{margin-left:5px;padding:3px 5px;border-radius:5px;background:#071522;color:#b8cde0}.wm-layers>span{margin-left:auto;color:#6f8da8;font-size:8px}
.wm-stage{position:relative}.wm-stage #globalWeatherMap{height:590px;background:#061421}.wm-legend{position:absolute;z-index:600;right:14px;top:14px;display:grid;gap:8px;min-width:155px;padding:12px;border:1px solid #2a526e;border-radius:10px;background:rgba(6,22,36,.94);box-shadow:0 9px 25px rgba(0,0,0,.4);backdrop-filter:blur(8px)}.wm-legend strong{color:#5e83a3;font-size:7px;letter-spacing:1px}.wm-legend span{color:#aac0d3;font-size:8px}.wm-legend i{display:inline-block;width:8px;height:8px;margin-right:6px;border-radius:50%}.wm-legend .observation{background:#8ea6bc}.wm-legend .rain{background:#1684ff}.wm-legend .storm{background:#8a5cff}.wm-legend .wind{background:#ef8d22}.wm-empty{position:absolute;z-index:650;top:50%;left:50%;transform:translate(-50%,-50%);padding:18px 25px;border:1px solid #2b526d;border-radius:11px;background:#071a2b;color:#7996af;text-align:center}.wm-empty i,.wm-empty strong,.wm-empty span{display:block}.wm-empty i{margin-bottom:8px;color:#4a94ce;font-size:23px}.wm-empty strong{color:#e4eff8;font-size:10px}.wm-empty span{font-size:8px}.wm-shell footer{display:flex;gap:20px;padding:9px 14px;border-top:1px solid #1b3d59;background:#071624;color:#66849e;font-size:8px}.wm-shell footer a{margin-left:auto;color:#62b3fa}.leaflet-popup-content-wrapper,.leaflet-popup-tip{background:#071a2b;color:#dbe9f5}.leaflet-popup-content-wrapper{border:1px solid #2a526e;border-radius:10px}.wm-popup-head{display:flex;align-items:center;gap:9px}.wm-popup-head img{width:37px;height:26px;border-radius:5px;object-fit:cover}.wm-popup-head h3{margin:0;color:#f0f7fd;font-size:12px}.wm-popup-head p{margin:2px 0 0;color:#7693ac;font-size:8px}.wm-popup-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:9px}.wm-popup-grid div{padding:7px;border:1px solid #193a54;border-radius:6px;background:#061522}.wm-popup-grid span,.wm-popup-grid strong{display:block}.wm-popup-grid span{color:#67859f;font-size:7px}.wm-popup-grid strong{color:#e9f3fc;font-size:9px}.wm-alerts{display:flex;flex-wrap:wrap;gap:4px;margin-top:7px}.wm-alerts b{padding:3px 6px;border-radius:5px;font-size:7px}.wm-alerts .rain{background:#103961;color:#62b3ff}.wm-alerts .storm{background:#302653;color:#b89dff}.wm-alerts .wind{background:#442b14;color:#ffb565}.wm-alerts .normal{background:#0c3528;color:#58df98}.wm-stage:fullscreen{background:#06111f}.wm-stage:fullscreen #globalWeatherMap{height:100vh}.wm-stage:fullscreen .wm-legend{top:22px;right:22px}
.wm-layers button.radar i{color:#42d6ff}.wm-layers button.radar.unavailable{border-color:#63313a;color:#e98791}.wm-layers button.radar.unavailable i{color:#ef6674}
@media(max-width:900px){.wm-stats{grid-template-columns:1fr 1fr}.wm-toolbar{flex-wrap:wrap}.wm-toolbar>div{width:100%}.wm-toolbar label{width:calc(100% - 170px)}}@media(max-width:600px){.wm-head{align-items:flex-start;flex-direction:column;gap:10px}.wm-stats{grid-template-columns:1fr}.wm-toolbar label{width:100%}.wm-layers{flex-wrap:wrap}.wm-layers>span{width:100%;margin:3px 0}.wm-stage #globalWeatherMap{height:500px}.wm-shell footer span:nth-child(2){display:none}}
</style>
@stop
@section('js')
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
const points=@json($weatherPoints),map=L.map('globalWeatherMap',{worldCopyJump:true,preferCanvas:true,minZoom:2}).setView([18,12],2);L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19,subdomains:'abcd',attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(map);L.control.scale({imperial:false,position:'bottomright'}).addTo(map);
const groups={observations:L.layerGroup().addTo(map),rain:L.layerGroup().addTo(map),storm:L.layerGroup().addTo(map),wind:L.layerGroup().addTo(map)},enabled={observations:true,rain:true,storm:true,wind:true};
let radarLayer=null,radarEnabled=true;
const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function popup(p){const code=safe(p.code).toLowerCase(),alerts=[p.rain?'<b class="rain">Rain / showers</b>':'',p.storm?'<b class="storm">Thunderstorm</b>':'',p.strong_wind?'<b class="wind">Strong wind</b>':''].filter(Boolean).join('')||'<b class="normal">Normal conditions</b>';return `<div class="wm-popup"><div class="wm-popup-head"><img src="https://flagcdn.com/w80/${code}.png" alt=""><div><h3>${safe(p.name)}</h3><p>${safe(p.capital||'National observation')} · ${safe(p.observed_at||'Latest')}</p></div></div><div class="wm-popup-grid"><div><span>Temperature</span><strong>${Number(p.temperature).toFixed(1)}°C</strong></div><div><span>Feels like</span><strong>${p.apparent_temperature==null?'—':Number(p.apparent_temperature).toFixed(1)+'°C'}</strong></div><div><span>Humidity</span><strong>${p.humidity==null?'—':Number(p.humidity).toFixed(0)+'%'}</strong></div><div><span>Pressure</span><strong>${p.pressure==null?'—':Number(p.pressure).toFixed(0)+' hPa'}</strong></div><div><span>Precipitation</span><strong>${Number(p.precipitation).toFixed(1)} mm</strong></div><div><span>Wind / gust</span><strong>${Number(p.wind).toFixed(1)} / ${Number(p.gust).toFixed(1)} km/h</strong></div></div><div class="wm-alerts">${alerts}</div></div>`}
function rebuild(code=''){Object.values(groups).forEach(group=>group.clearLayers());const visible=points.filter(p=>!code||p.code===code);visible.forEach(p=>{const html=popup(p),coords=[p.lat,p.lon];L.circleMarker(coords,{radius:3,color:'#8ea6bc',weight:1,fillColor:'#8ea6bc',fillOpacity:.6}).bindPopup(html).addTo(groups.observations);if(p.rain)L.circleMarker(coords,{radius:Math.min(14,6+Number(p.precipitation)),color:'#b9dcff',weight:1.5,fillColor:'#1684ff',fillOpacity:.78}).bindPopup(html).addTo(groups.rain);if(p.storm)L.circleMarker(coords,{radius:11,color:'#e3d8ff',weight:2,fillColor:'#8a5cff',fillOpacity:.9}).bindPopup(html).addTo(groups.storm);if(p.strong_wind)L.circleMarker(coords,{radius:Math.min(14,6+Number(p.wind)/15),color:'#ffe0bd',weight:1.5,fillColor:'#ef8d22',fillOpacity:.84}).bindPopup(html).addTo(groups.wind)});Object.keys(groups).forEach(key=>enabled[key]?groups[key].addTo(map):map.removeLayer(groups[key]));document.getElementById('weatherVisibleCount').textContent=visible.length;document.getElementById('observationLayerCount').textContent=visible.length;document.getElementById('rainLayerCount').textContent=visible.filter(p=>p.rain).length;document.getElementById('stormLayerCount').textContent=visible.filter(p=>p.storm).length;document.getElementById('windLayerCount').textContent=visible.filter(p=>p.strong_wind).length;document.getElementById('weatherMapEmpty').hidden=visible.length>0;if(visible.length&&code){map.setView([visible[0].lat,visible[0].lon],5)}else map.setView([18,12],2)}
document.querySelectorAll('[data-weather-layer]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.weatherLayer;enabled[key]=!enabled[key];button.classList.toggle('active',enabled[key]);enabled[key]?groups[key].addTo(map):map.removeLayer(groups[key])}));const filter=document.getElementById('weatherCountryFilter');filter.addEventListener('change',()=>rebuild(filter.value));document.getElementById('resetWeatherMap').addEventListener('click',()=>{filter.value='';rebuild()});const stage=document.querySelector('.wm-stage');document.getElementById('weatherMapFullscreen').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():stage.requestFullscreen());document.addEventListener('fullscreenchange',()=>setTimeout(()=>map.invalidateSize(),150));rebuild(new URLSearchParams(location.search).get('country')||'');
const radarButton=document.getElementById('radarLayerToggle'),radarStatus=document.getElementById('radarStatus'),radarTimestamp=document.getElementById('radarTimestamp');
radarButton.addEventListener('click',()=>{if(!radarLayer)return;radarEnabled=!radarEnabled;radarButton.classList.toggle('active',radarEnabled);radarEnabled?radarLayer.addTo(map):map.removeLayer(radarLayer)});
fetch('https://api.rainviewer.com/public/weather-maps.json').then(response=>{if(!response.ok)throw new Error('Radar metadata unavailable');return response.json()}).then(data=>{const frame=data?.radar?.past?.at(-1);if(!frame||!data.host)throw new Error('No radar frame');radarLayer=L.tileLayer(`${data.host}${frame.path}/512/{z}/{x}/{y}/2/1_1.png`,{tileSize:512,zoomOffset:-1,maxNativeZoom:7,maxZoom:18,opacity:.58,zIndex:250,attribution:'Radar &copy; RainViewer'});if(radarEnabled)radarLayer.addTo(map);radarStatus.textContent='LIVE';radarTimestamp.innerHTML=`<i class="fas fa-clock"></i> Radar ${new Date(frame.time*1000).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB`}).catch(()=>{radarEnabled=false;radarButton.classList.remove('active');radarButton.classList.add('unavailable');radarStatus.textContent='OFF';radarTimestamp.innerHTML='<i class="fas fa-exclamation-triangle"></i> Radar unavailable - observation markers remain active'});
</script>
@stop
